import os

API_SECRET_KEY = os.getenv("API_SECRET_KEY")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 10080  # 1 week
SQLALCHEMY_DATABASE_URL = os.getenv("DATABASE_URL")
REDIRECT_URL = os.getenv("REDIRECT_URL")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_SUB_PRICE_ID = os.getenv("STRIPE_SUB_PRICE_ID")
